import { Metadata } from 'next';
import FilterAndCards from './components/FilterAndCards';

export const metadata: Metadata = {
	title: 'MarketPlace',
	description: 'Generated by create next app',
};



export default function MarketPlacePage() {
	return (
		<div className='w-full '>
			<FilterAndCards />
		</div>
	);
}
