import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'MarketPlace',
	description: 'Generated by create next app',
};

export default function MarketPlacePage() {
	return <div className=''>Marketplace</div>;
}
