import type { Metadata } from 'next';
import { Space_Mono } from 'next/font/google';
import './globals.css';
import TheFooter from '@/components/theFooter/TheFooter';
import TheHeader from '@/components/theHeader/TheHeader';

const spaceMono = Space_Mono({ weight: ['400'], subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={spaceMono.className}>
				<TheHeader />
				{/* <div className='mx-[115px]'>{children}</div> */}
				<div className='flex justify-center'>{children}</div>
				<TheFooter />
			</body>
		</html>
	);
}
