import type { Metadata } from 'next';
import { Space_Mono, Work_Sans } from 'next/font/google';
import './globals.css';
import TheFooter from '@/components/theFooter/TheFooter';
import TheHeader from '@/components/theHeader/TheHeader';
import { ReduxProvider } from '@/redux/provider';

const spaceMono = Space_Mono({ weight: ['400', '700'], subsets: ['latin'] });
const workSans = Work_Sans({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
	modal,
}: {
	children: React.ReactNode;
	modal: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={`${spaceMono.className}, ${workSans.className}`}>
				<ReduxProvider>
					<TheHeader />
					<div className='flex justify-center text-white'>
						{children} {modal}
					</div>
					<TheFooter />
				</ReduxProvider>
			</body>
		</html>
	);
}
